# Site
repository: immiora.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julia Berezutskaya
title: Postdoctoral Researcher @Radboud University
email: yuliya.berezutskaya@donders.ru.nl
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ju_berezutskaya
github_username:  immiora
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: juliaberezutskaya
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: S3Xx9ccAAAAJ

# Additional icon links
additional_links:
#- title: google_scholar
#  icon: fab fa-google
#  url: https://scholar.google.com/citations?user=S3Xx9ccAAAAJ&hl=en
- title: cv
  icon: far fa-file-pdf #(https://fontawesome.com/icons?d=gallery&m=free)
  url: https://immiora.github.io/cv/assets/CV_Julia.docx.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I focus on computational modeling of speech processes in the human brain. I try to bring together people working on natural language processing, machine learning, computational neuroscience and clinical neuroscience so that we can build powerful models of speech production and perception in the brain. Not only are such models important for our fundamental understanding of how the brain works, they are essential for development of assistive neurotechnology and brain-computer interfaces that can restore cognitive function in patients, such as communication via decoding of attempted speech in paralyzed individuals.
  
  I am committed to open reproducible science: I publish open-access and do my best to share code and data of every published project.
  
  Most of my projects revolve around <mark>neuroscience</mark>, <mark>machine learning</mark>, <mark>language</mark> and <mark>brain-computer interfaces</mark>.
  
#  <br>
#  <br>
#  <p style="text-align:center;"><a class="twitter-timeline" data-width="500" href="https://twitter.com/ju_berezutskaya?ref_src=twsrc%5Etfw">Tweets by ju_berezutskaya</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

#I am most skilled in: 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Open Multimodal IEEG-FMRI Dataset (63 subjects)
        link: https://openneuro.org/datasets/ds003688/versions/1.0.6
        # link_text: Project Website
        additional_links:
          - title:  Publication
            icon: far fa-sticky-note
            url: https://www.biorxiv.org/content/10.1101/2021.06.09.447733v1.full
          - title:  Dataset
            icon: fas fa-database
            url: https://openneuro.org/datasets/ds003688/versions/1.0.6
          - title:  Github repository
            icon: fab fa-github
            url: https://github.com/UMCU-RIBS/ieeg-fmri-dataset-validation
          - title:  Youtube video
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=C14cWM1CvrE&t=17s&ab_channel=UMCURIBS 
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          We were among the first teams to publicly share human intracranial brain data from a cognitive task. Sixty subjects watched a short film while their brain responses were collected using electrocorticography or stereoelectroencephalography. In addition, for many subjects we provide functional magnetic resonance imaging data acquired during the same task. We share the data for public use by researchers in cognitive neuroscience and other fields.
          
          - Berezutskaya, J., Vansteensel, M.J., Aarnoutse, E.J., Freudenburg, Z.V., Piantoni, G., Branco, M.P. & Ramsey, N.F. (2021). Open multimodal iEEG-fMRI dataset from naturalistic stimulation with a short audiovisual film. (article). *bioRxiv*. doi: [10.1101/2021.06.09.447733](https://doi.org/10.1101/2021.06.09.447733)
          
      - layout: top-middle
        title: Language in Interaction
        link: https://www.languageininteraction.nl/
        description: | # this will include new lines to allow paragraphs
          Within [Big Question 1](https://www.languageininteraction.nl/research-organization/big-questions/big-question-1/) our team works on computational modeling of language processing in the brain. I develop neural encoding and decoding models that help us understand how the brain processes speech.
          
          - Berezutskaya, J., Freudenburg, Z.V., Ambrogioni, L., Güçlü, U., Gerven, M.A.J. van & Ramsey, N.F. (2020). Cortical network responses map onto data-driven features that capture visual semantics of movie fragments. *Scientific Reports*, 10:12077. doi: [10.1038/s41598-020-68853-y](https://doi.org/10.1038/s41598-020-68853-y)
          
          - Berezutskaya, J., Freudenburg, Z.V., Güçlü, U., Gerven, M.A.J. van & Ramsey, N.F. (2020). Brain-optimized extraction of complex sound features that drive continuous auditory perception. *Plos Computational Biology*, 16 (7):e1007992. doi: [10.1371/journal.pcbi.1007992](https://doi.org/10.1371/journal.pcbi.1007992)
          
          - Berezutskaya, J., Baratin, C., Freudenburg, Z.V. & Ramsey, N.F. (2020). High-density intracranial recordings reveal a distinct site in anterior dorsal precentral cortex that tracks perceived speech. *Human Brain Mapping*, 41 (16), 4587-4609. doi: [10.1002/hbm.25144](https://doi.org/10.1002/hbm.25144) 
          
          - Berezutskaya, Y., Freudenburg, Z.V., Güçlü, U., Gerven, M.A.J. van & Ramsey, N.F. (2017). Neural tuning to low-level features of speech throughout the perisylvian cortex. *The Journal of Neuroscience*, 37 (33), 7906-7920. doi: [10.1523/JNEUROSCI.0238-17.2017](https://doi.org/10.1523/JNEUROSCI.0238-17.2017)
          
      - layout: top-middle
        title: INTENSE
        link: https://intenseproject.eu/
        description: | # this will include new lines to allow paragraphs
          Within [WP-B](https://intenseproject.eu/work-packages/artificial-intelligence) our team uses recent advances in computational modeling and artificial intelligence for development of real-wordl clinical applications in the field on neurotechnology. My work focuses on models for speech decoding and reconstruction from intracranial brain activity. My goal is to build and validate brain-computer interface solutions for severely paralyzed individuals and provide them with means of communication with the outside world.
#
#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
#         # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
#
#   - title: Education # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: Harvard University
#         caption: 2010 - 2013
#         sub_title: BSc Computer Science
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#         description: | # this will include new lines to allow paragraphs
#           During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#
#           I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
#
  - title: Twitter Feed
    layout: text
    content: | # this will include new lines to allow paragraphs
      <p style="text-align:center;"><a class="twitter-timeline" data-width="500" href="https://twitter.com/ju_berezutskaya?ref_src=twsrc%5Etfw">Tweets by ju_berezutskaya</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

# Footer
footer_show_references: true
references_title: 2022

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
